2021-12-26 21:04:31,550 INFO    MainThread:3820 [wandb_setup.py:_flush():71] setting env: {}
2021-12-26 21:04:31,550 INFO    MainThread:3820 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-26 21:04:31,550 INFO    MainThread:3820 [wandb_init.py:_log_setup():371] Logging user logs to /Users/davnguye/nonwork/fyoudie/python_workbooks/wandb/run-20211226_210431-2kbql08x/logs/debug.log
2021-12-26 21:04:31,551 INFO    MainThread:3820 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/davnguye/nonwork/fyoudie/python_workbooks/wandb/run-20211226_210431-2kbql08x/logs/debug-internal.log
2021-12-26 21:04:31,551 INFO    MainThread:3820 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fda283e4d60>
2021-12-26 21:04:31,551 INFO    MainThread:3820 [wandb_init.py:init():404] calling init triggers
2021-12-26 21:04:31,551 INFO    MainThread:3820 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-26 21:04:31,551 INFO    MainThread:3820 [wandb_init.py:init():460] starting backend
2021-12-26 21:04:31,551 INFO    MainThread:3820 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-12-26 21:04:31,674 INFO    MainThread:3820 [backend.py:ensure_launched():216] starting backend process...
2021-12-26 21:04:31,687 INFO    MainThread:3820 [backend.py:ensure_launched():221] started backend process with pid: 3974
2021-12-26 21:04:31,692 INFO    MainThread:3820 [wandb_init.py:init():469] backend started and connected
2021-12-26 21:04:31,756 INFO    MainThread:3820 [wandb_run.py:_label_probe_notebook():911] probe notebook
2021-12-26 21:04:31,756 INFO    MainThread:3820 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-12-26 21:04:31,756 INFO    MainThread:3820 [wandb_init.py:init():533] updated telemetry
2021-12-26 21:04:31,785 INFO    MainThread:3820 [wandb_init.py:init():563] communicating current version
2021-12-26 21:04:33,496 INFO    MainThread:3820 [wandb_init.py:init():568] got version response 
2021-12-26 21:04:33,496 INFO    MainThread:3820 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2021-12-26 21:04:33,703 INFO    MainThread:3820 [wandb_init.py:init():606] starting run threads in backend
2021-12-26 21:04:37,147 INFO    MainThread:3820 [wandb_run.py:_console_start():1810] atexit reg
2021-12-26 21:04:37,148 INFO    MainThread:3820 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2021-12-26 21:04:37,149 INFO    MainThread:3820 [wandb_run.py:_redirect():1721] Wrapping output streams.
2021-12-26 21:04:37,149 INFO    MainThread:3820 [wandb_run.py:_redirect():1745] Redirects installed.
2021-12-26 21:04:37,149 INFO    MainThread:3820 [wandb_init.py:init():633] run started, returning control to user process
2021-12-26 21:04:37,153 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:04:37,153 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:04:45,430 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:04:47,610 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:04:47,611 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:05:01,659 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:05:04,181 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:05:04,181 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:05:04,186 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:06:20,205 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:06:20,206 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:06:39,654 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:06:45,046 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:06:45,046 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:06:45,659 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:07:12,869 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:07:12,869 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:07:14,391 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:07:15,523 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:07:15,524 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:07:15,535 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:12:15,683 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:12:15,684 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:12:16,440 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:12:16,533 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:12:16,533 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:12:24,712 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:12:30,206 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:12:30,207 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:12:34,853 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:12:40,472 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:12:40,472 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:14:21,655 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:14:27,671 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:14:27,671 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:14:47,374 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:14:47,392 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:14:47,393 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:15:21,896 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:15:28,204 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:15:28,204 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:15:45,372 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:15:45,499 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:15:45,499 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:15:57,067 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:16:03,109 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:16:03,109 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:16:20,652 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:16:22,428 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:16:22,428 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:16:27,685 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:16:38,005 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:16:38,005 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:16:48,885 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:16:48,903 INFO    MainThread:3820 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-26 21:16:48,903 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:17:15,008 INFO    MainThread:3820 [wandb_init.py:_resume_backend():293] resuming backend
2021-12-26 21:17:15,027 INFO    MainThread:3820 [wandb_setup.py:_flush():71] setting env: {}
2021-12-26 21:17:15,027 INFO    MainThread:3820 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-26 21:17:15,027 INFO    MainThread:3820 [wandb_init.py:_log_setup():371] Logging user logs to /Users/davnguye/nonwork/fyoudie/python_workbooks/wandb/run-20211226_211715-1xyyn6zr/logs/debug.log
2021-12-26 21:17:15,028 INFO    MainThread:3820 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/davnguye/nonwork/fyoudie/python_workbooks/wandb/run-20211226_211715-1xyyn6zr/logs/debug-internal.log
2021-12-26 21:17:15,028 INFO    MainThread:3820 [wandb_init.py:init():404] calling init triggers
2021-12-26 21:17:15,028 INFO    MainThread:3820 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-26 21:17:15,028 INFO    MainThread:3820 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 2kbql08x
2021-12-26 21:17:15,029 INFO    MainThread:3820 [wandb_run.py:finish():1457] finishing run dhn045/fyoudie/2kbql08x
2021-12-26 21:17:15,030 INFO    MainThread:3820 [jupyter.py:save_history():429] not saving jupyter history
2021-12-26 21:17:15,030 INFO    MainThread:3820 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-26 21:17:15,030 INFO    MainThread:3820 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2021-12-26 21:17:15,030 INFO    MainThread:3820 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2021-12-26 21:17:15,031 INFO    MainThread:3820 [wandb_run.py:_restore():1752] restore
2021-12-26 21:17:15,629 INFO    MainThread:3820 [wandb_run.py:_restore():1752] restore
2021-12-26 21:17:15,646 ERROR   MainThread:3820 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1963, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 45, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/davnguye/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
